version: '3'
services:
  media_manager:
    build: .
    container_name: media_metadata_manager
    ports:
      - "8020:80"
    image: lucas42/lucos_media_metadata_manager
    restart: always
    environment:
      - KEY_LUCOS_MEDIA_METADATA_API
      - MEDIA_API=https://media-api.l42.eu